quarkus.swagger-ui.always-include=true
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.host=0.0.0.0
quarkus.http.enable-compression=true
quarkus.devservices.enabled=false
quarkus.tls.trust-all=true
quarkus.kubernetes-client.trust-certs=true


quarkus.rest-client.actions_openapi_json.url=${ORCHESTRATOR_URL:http://host.docker.internal:7007/api/orchestrator}
quarkus.rest-client.retrigger_openapi_json.url=http://host.docker.internal:8008
quarkus.rest-client.patch_k8s_resource_yaml.url=https://api.ocp-edge-orchestrator-0.qe.lab.redhat.com:6443
quarkus.openapi-generator.patch_k8s_resource_yaml.auth.BearerToken.bearer-token=sha256~j-uYJRecnVz6gdFGoZV26JauZaitSJlZgB0P0n4VDUw

mp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http
mp.messaging.incoming.kogito_incoming_stream.path=/


quarkus.log.category."org.apache.http".level=DEBUG
#quarkus.log.level=INFO
